apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: dpk6-executor
  namespace: testkube
spec:
  executor_type: job
  # not best practice but for now we use latest
  image: kubeshop/testkube-dpk6-executor:latest
  # image: lreimer/testkube-k6-executor:latest
  types:
  - dpk6/script
  - dpk6/run
  - dpk6/cloud
